### ISSUE TITLE
No longer a secondary nav option Theme Settings

### ISSUE THREAD

**Issue by laras126** [billerickson/Genesis-Subpages-as-Secondary-Menu#5]
Unless I am seriously missing something, it looks like there isn't an option to enable the Secondary nav anymore (Genesis > Theme Settings > Navigation Settings), and that now it is enabled by assigning a menu to it in Appearance > Menus. The plugin seems to work fine by overriding the selected menu, but it'd be helpful to update the documentation.

Thanks for all your work on this! Excellent tool.

**Comment by joshrogersdesign** [comment]
Yes! jarcox - you just solved my problem for me! Making the subpages attached to a parent page seems obvious now, but I could NOT figure it out until I read your comment. 

Thanks!

**Comment by billerickson** [comment]
Correct, this plugin is based on the PAGE hierarchy - it does not look at what is in the menu.

If you want it baed on MENU hierarchy (and are comfortable writing code), then use this: http://www.billerickson.net/code/submenu-items-in-secondary-menu/

**Comment by joshrogersdesign** [comment]
Thanks Bill! I am gonna try that one out. Seems like it could be more of what I am needing.

**Comment by joshrogersdesign** [comment]
Great work btw!
