### ISSUE TITLE
Subpages menu not appearing unless other menu assigned 

### ISSUE THREAD

**Issue by flyingpylon** [billerickson/Genesis-Subpages-as-Secondary-Menu#6]
I've been using the Genesis Subpages as Secondary Menu plugin for quite some time and recently discovered this issue. I am running v1.8 of the plugin on all sites in a multisite network running WP 4.0 and Genesis 2.1.2, and the subpages menu is always displayed in the primary sidebar.

On a few of the sites, nothing appears where the subpages menu should be.  I have found that on the problem sites, I need to create a dummy menu and assign it to the secondary menu position before the plugin will display the subpages menu.  If I set the secondary menu assignment back to no menu (or a blank menu with no items) then the subpages menu will not be displayed.

Very strange that this only occurs on some sites and not others.  I have verified that the sites that have always worked do not have any menus assigned to the secondary menu location.  The problem sites are not new sites either, they had been working fine previously.

**Comment by billerickson** [comment]
This was resolved in the latest rewrite
