### ISSUE TITLE
How to disable child links

### ISSUE THREAD

**Issue by michaeldemi** [billerickson/Genesis-Subpages-as-Secondary-Menu#8]
Hey,

I'm working on a site that has a lot of sub menus 
for example
- Menu L1 A
  -  Menu L2
    - Menu L3 a
    - Menu L3 b
    - Menu L3 c
    - Menu L3 d
    - Menu L3 e
- Menu L1 
  -  Menu L2
    - Menu L3 a
    - Menu L3 b
    - Menu L3 c
    - Menu L3 d
    - Menu L3 e

and etcetera, is there a way to hide L3 menu until you enter L2? 

Any help is greatly appriciated!

Thanks,
Michael

**Comment by billerickson** [comment]
Yes, by limiting the depth of that menu location. Assuming you're using the 'primary' menu, add the following to your theme's functions.php file: https://gist.github.com/billerickson/534869d020998c747af9

Now the primary menu will only show L1 and L2 menu items. The secondary menu will show L2 and L3.

**Comment by michaeldemi** [comment]
Thank you so much !

**Comment by michaeldemi** [comment]
Hey I don't think I did a great job explaining what I meant, does this make more sense ?.

![hide subpages](https://cloud.githubusercontent.com/assets/5803071/13673140/bd68dc3e-e6a5-11e5-8d11-f07700c82754.png)

**Comment by billerickson** [comment]
This plugin should only be used for the menu at the top of the page, not for the sidebar. For that you should use [BE Subpages Widget](https://github.com/billerickson/be-subpages-widget).
